### ISSUE TITLE
Function example for output in Readme

### ISSUE THREAD

**Issue by natejacobson** [xwp/wp-shortcode-ui-richtext#1]
Great work here on this plugin, and I'm really hoping it comes to fruition. Code hack that I am, I've had a hard time on the output side. Bootstrap editor is loading, content is being encoded, but I'm unsure how to decode for the shortcode output, so I'm only seeing the encoded content. It would be great to add an example for the `add_shortcode` function. My attempt to use html_entity_decode on `$body`, which has `encode => true` failed.

``` php
function aside_shortcode( $atts ) {
    extract( shortcode_atts(
        array(
         'header' => '',
         'body' => '',
        ),
        $atts
    ));
    return '<aside><header>'.$header.'</header>'.html_entity_decode($body)'</aside>';
}
add_shortcode( 'aside', 'aside_shortcode' );
```

I'm guessing I'm just going about this in the wrong way, so an example would probably be all I and others need.

**Comment by mehigh** [comment]
Hello Nate,

That's an issue I stacked _for later_... and yes, I experience the same. Whenever encode is set to true, the visual editor shows the shortcake with the encoded string... just like this:
![URL Encoded string](http://files.urldocs.com/share/Screen-Shot-2016-08-29-at-17.01.59/Screen-Shot-2016-08-29-at-17.01.59.png)
On the website, the text shows up properly.

But that's not html entity encoded... it's URL encoded instead

You can use this tool as an example:
http://meyerweb.com/eric/tools/dencoder/
and once you pass in the code in there, you'll see it generates the proper values.

A hint on how you can detect URL encoded strings - is to notice the "%20" that comes up often. That's how you URL encode the space character.

So maybe give it another shot like this:

``` php
function aside_shortcode( $atts ) {
    extract( shortcode_atts(
        array(
         'header' => '',
         'body' => '',
        ),
        $atts
    ));
    return '<aside><header>'.$header.'</header>'. urldecode($body)'</aside>';
}
add_shortcode( 'aside', 'aside_shortcode' );
```

See if this gets you closer to success. (I've just replaced the `html_entity_decode` call by `urldecode`)

**Comment by natejacobson** [comment]
That did the trick, @mehigh. Again, thanks. This plugin was a godsend for me. I also didn't see anything in your documentation about how to apply the Summernote editor to an inner_content textarea, but this worked for me:

``` js
var richTextSelector = 'textarea.shortcake-richtext,textarea#inner_content';
```

For whatever reason, adding `'class' => 'shortcake-richtext',` to `inner_content` does not successfully add that class to the inner content textarea. I imagine a lot of others would like the inner_content area to be wysiwyg by default when activating your plugin.

**Comment by mehigh** [comment]
I'll add this to the readme, thank you!

**Comment by mehigh** [comment]
Added the urldecode to the documentation here:
https://github.com/xwp/wp-shortcode-ui-richtext/pull/3

**Comment by mehigh** [comment]
Added the rich text editing to the short-code inner content area here:
https://github.com/xwp/wp-shortcode-ui-richtext/pull/4
