### ISSUE TITLE
Issue and fix with/for multiple editors

### ISSUE THREAD

**Issue by scottpoulin** [xwp/wp-shortcode-ui-richtext#11]
Hi,

Great extension to a great plugin... gives clients a nice UI without getting dragged into those horrible page builders etc.  Anyway, I was running into an issue with multiple TinyMCE editors for a given post/page, for example using one for a post meta in addition to the main editor.  Problem was that using a shortcake rich text editor would always send the content back to the main WP editor, not the one I was working in.

Solution, modifications to js/richtext.js:

```
/* globals jQuery, alert */
jQuery(function( $ ) {
	'use strict';

	var richTextSelector = 'textarea.shortcake-richtext, #inner_content';
	var richText = {};
	var currentEditor;	// var to save current editor

	/**
	 * Loads tinyMCE rich text editor.
	 *
	 * @param {string} selector
	 * @returns {boolean}
	 */
	richText.load = function( selector ) {
		currentEditor = wpActiveEditor;
		
		if ( ( 'undefined' !== tinyMCE ) && ( $( selector ).length ) ) {
			$( selector ).each( function() {

				var textarea_id = $(this).attr('id');

				if( null === tinyMCE.get( textarea_id ) ) {

					// Add a slight delay to offset the loading of any elements on the page. Sometimes doesn't load correctly
					setTimeout(function () {
						// Bind tinyMCE to this field
						tinyMCE.execCommand('mceAddEditor', false, textarea_id );
						tinyMCE.execCommand('mceAddControl', false, textarea_id );
					}, 200);

				}

			});

			return true;
		} else {
			return false;
		}
	};

	/**
	 * Unloads tinyMCE rich text editor.
	 *
	 * @param {string} selector
	 * @returns {boolean}
	 */
	richText.unload = function( selector ) {
		if ( ( $( selector ).length ) ) {
			$( selector ).each( function() {
				var textarea_id = $( this).attr('id');

				$( this )
					.text( tinyMCE.get( textarea_id ).getContent() )
					.trigger( 'input' );

				// Remove tinyMCE from the field
				tinymce.execCommand( 'mceRemoveEditor', true, textarea_id );
			});

			// Switch the global active editor back to the WordPress editor
			//wpActiveEditor = 'content';
			wpActiveEditor = currentEditor;

			return true;
		} else {
			return false;
		}
	};

	wp.shortcake.hooks.addAction( 'shortcode-ui.render_edit', function() {

		// Dynamically bind to newly inserted elements as the action is fired after the field has been added
		$(document).bind( 'DOMNodeInserted', function(e) {
			var element = e.target;

			if( $( element ).hasClass( 'shortcode-ui-content-insert' ) ) {
				richText.loaded = richText.load( $( element ).find( richTextSelector ) );
			}

		});

		richText.loaded = richText.load( richTextSelector );
	} );
	wp.shortcake.hooks.addAction( 'shortcode-ui.render_new', function() {
		richText.loaded = richText.load( richTextSelector );
	} );
	wp.shortcake.hooks.addAction( 'shortcode-ui.render_destroy', function() {
		if ( richText.loaded ) {
			richText.unload( richTextSelector );
		}
	} );

} );

```

**Comment by mehigh** [comment]
Hi Scott,

Thank you for the appreciation and the solution to your problem.

Can you please provide more details onto what environment / actual setup you were using when experiencing the glitch? I'd like to replicate it before patching this.

Also, since this isn't a pull request, I don't have a diff out of the box, but please confirm whether this was the only code change:
```php
// wpActiveEditor = 'content';
wpActiveEditor = currentEditor;
```

**Comment by scottpoulin** [comment]
Sorry, should have done it as a pull but I am scrambling before a trip.

Environment: developing locally on top of WAMP, WP 4.75, versions of shortcake & your extension downloaded this week.  Working in Chrome.  For Pages, I have a second TinyMCE set up in a meta box, below the main one. Then I have a shortcode ui that uses (your) rich text editor along with a title field.

In the main WP editor all works fine.  In the second meta box, after inserting the new element it gets dropped into the main editor rather than the meta box editor.

My solution was a guess, hoping that wpActiveEditor was global.  So before your extension creates a new editor, the currently active one gets saved to the new var currentEditor.

Changes:
after
`var richText = {};`
add
`var currentEditor;	// var to save current editor`

after
`richText.load = function( selector ) {`
add
`currentEditor = wpActiveEditor;`

and inside richText.unload, the change you noted.

**Comment by mehigh** [comment]
Thank you. That's much better and I clearly understand the issue you were facing. 

Have a great trip!
I'll test it out and release it in the next version.
