### ISSUE TITLE
Content returned to WP Editor is encoded

### ISSUE THREAD

**Issue by tmconnect** [xwp/wp-shortcode-ui-richtext#12]
_I hope this is the right wording. Because I'm no native english speaker..._

The content I get from the popup into the WP editor looks like this:

[pullquote text="This%20is%20my%20content%20of%20the%20Rich-Text-Editor" /]

Blanks are encoded with %20%

**Comment by mehigh** [comment]
Hello @tmconnect 

Thank you for your report. 

This is normal behaviour as without encoding the shortcodes would break whenever common characters that appear in HTML appear (like the double quotes in links <a href=**"..."**). 

This is explained in the plug-in's readme:
_Due to the possibility of the user entered content to contain special characters like [, ] and ", it is highly recommended to turn on the encode flag as well._

The decode is supposed to happen in the shortcode itself:
`return '<div>' . urldecode( $text_element ) . '</div>';`

Therefore, as long as you see the text showing up properly on the website, you've set things up correctly.
