### ISSUE TITLE
Configure the editor toolbar (use minimal)?  Optionally remove 'Add Media'?

### ISSUE THREAD

**Issue by m9n** [xwp/wp-shortcode-ui-richtext#23]
Thanks so much for this plugin ❤️

Is it possible to pass arguments through to the TinyMCE editor?  I'd like to remove the "Add Media" button, and choose the minimal button set.

**Comment by mehigh** [comment]
Thank you for the appreciation @m9n 
With Gutenberg just around the corner these sort of 'hack-ish' implementations will be slowly but surely fade away. 
In just a couple of months solutions like this would be possible directly in the main editor flow as a rich text block and there wouldn't be any need for shortcode-ui or such add-ons like this one.

If I were you I'd keep an eye on Gutenberg blocks and plug-ins adding such elements and try to use those instead.
Thanks for the suggestion though.
