### ISSUE TITLE
Not working for theme shortcodes

### ISSUE THREAD

**Issue by rebekah-sofo** [xwp/wp-shortcode-ui-richtext#5]
I'm encountering a strange issue where this works fine for custom plugin shortcodes -- the richtext editor displays for both attribute fields and inner content. However, it doesn't work properly for theme shortcodes. If I load the edit screen and edit or add a shortcode that was created via the theme, the richtext fields are displaying as standard, non-richtext textareas (for both attribute and inner content); but, if I go to edit/add a shortcode from a plugin, then go back to editing the theme shortcode instance, the fields are suddenly richtext. It seems like there's some hook for the richtext fields that is firing differently for theme vs plugin shortcodes, but I can't figure out why.

**Comment by mehigh** [comment]
Can you compare the way they are initialised inside the plug-in vs. inside the theme? Maybe there's a class missing for the theme shortcodes. 

This plug-in expects a certain class to be present before the rich text kicks in.

**Comment by rebekah-sofo** [comment]
There doesn't seem to be any difference. And since we mainly need it for the inner content, that's all I'm focusing on for now (i.e., we're not turning any of the attribute fields into richtext inputs). And as the plugin seems to automatically convert the inner content area into richtext, I'm not adding/changing anything about the shortcodes.

On the other hand, it looks like we were already considering pulling the theme shortcodes out and putting them into a plugin, so we may be able to avoid this issue entirely, if that works out.

**Comment by mehigh** [comment]
I've primarily used this as theme-defined shortcodes, and only had a few plug-ins with shortcodes since the creation of this plug-in. It all worked out without a hitch. 

Can you check your browser console and see if you get any javascript errors when trying to add a theme shortcode, which might be different than what console is giving you when adding plug-in based shortcodes?

**Comment by rebekah-sofo** [comment]
Ah! Yes, it was a completely unrelated error from a new bit of functionality in the theme. I checked the console earlier, but didn't see the error at that time. Looks like it's working now, thank you!

**Comment by mehigh** [comment]
I'm glad you got it fixed!
