### ISSUE TITLE
List items appear unstyled in the editor

### ISSUE THREAD

**Issue by pyronaur** [xwp/wp-shortcode-ui-richtext#6]
Wordpress `wp-admin/css/common.css @ line 362` in version 4.7.1 removes list styles. As a result - the plugin has no list styles when editing.

An easy fix, but a serious issue for regular users who will try to add a list item, but won't see any visual feedback.

**Comment by mehigh** [comment]
Fixed with the #9 TinyMCE update. Now the TinyMCE styles come through and the lists have bullets - both ordered and unordered lists.
