### ISSUE TITLE
Editing Shortcake Shortcodes Doesn't Initialize Text Editor

### ISSUE THREAD

**Issue by bengreeley** [xwp/wp-shortcode-ui-richtext#7]
Hi Mike,

I noticed when I was testing this plugin that when I create a shortcode with a rich text editor area it displays fine, but when I edit that area again the richt text editor JS code never loads. I'm not sure if it has to do with my WordPress or Shortcake version, but WP version is 4.7.3, Shortcake version is 0.7.1.

I traced this to line 44 in richtext.js, which seems to fire the hook before the element is ever added to the page. I got around this by adding the following for that line:
```

wp.shortcake.hooks.addAction( 'shortcode-ui.render_edit', function() {

		$(document).bind('DOMNodeInserted', function(e) {
			var element = e.target;

			if( $( element ).hasClass( 'shortcode-ui-content-insert' ) ) {
				richText.loaded = richText.load( $( element ).find( richTextSelector ) );
			}

		});

		richText.loaded = richText.load( richTextSelector );
	} );
```
There's probably a better way around this, but wanted to give you a heads-up. Thanks for creating the plugin by the way!

**Comment by mehigh** [comment]
Thanks for the input @bengreeley 
I'll make sure to incorporate your suggestion in the next release of the plug-in after testing it on a bare WP / Shortcake setup.

**Comment by mehigh** [comment]
I see this update was part of your PR #8 , which now is merged into master. 
The contribution gets the job done, and that's all that matters. 

Closing the issue as the code is going in the next release.
